CREATE SEQUENCE AUTEUR_SEQ INCREMENT BY 1 START WITH 20;

CREATE OR REPLACE FUNCTION CREER_AUTEUR(VAL_NOM IN AUTEUR.NOM%TYPE, VAL_PRENOM IN AUTEUR.PRENOM%TYPE) RETURN AUTEUR.ID_AUTEUR%TYPE IS
    VAL_NEW_ID AUTEUR.ID_AUTEUR%TYPE;
    IS_EXISTING NUMBER;
BEGIN
    SELECT COUNT(*) INTO IS_EXISTING FROM AUTEUR WHERE NOM = VAL_NOM AND PRENOM = VAL_PRENOM;

    IF IS_EXISTING > 0 THEN
        RAISE_APPLICATION_ERROR(-20001, 'L''auteur existe déjà.');
        RETURN 0;
    END IF;

    SELECT AUTEUR_SEQ.NEXTVAL INTO VAL_NEW_ID FROM DUAL;
    INSERT INTO AUTEUR (ID_AUTEUR, NOM, PRENOM) VALUES (VAL_NEW_ID, VAL_NOM, VAL_PRENOM);
    COMMIT;

    RETURN VAL_NEW_ID;
END;


CREATE OR REPLACE PROCEDURE SUPPRIMER_AUTEUR(VAL_ID_AUTEUR AUTEUR.ID_AUTEUR%TYPE) IS
    IS_EXISTING NUMBER;
BEGIN
    SELECT COUNT(*) INTO IS_EXISTING FROM AUTEUR WHERE ID_AUTEUR = VAL_ID_AUTEUR;
    IF IS_EXISTING > 0 THEN
        DELETE FROM LIVRE WHERE ID_AUTEUR = VAL_ID_AUTEUR;
        DELETE FROM AUTEUR WHERE ID_AUTEUR = VAL_ID_AUTEUR;
        COMMIT;
    ELSE
        RAISE_APPLICATION_ERROR(-20002, 'L''auteur n''existe pas.');
    END IF;
END;


CREATE OR REPLACE PROCEDURE MODIFIER_AUTEUR(VAL_ID_AUTEUR AUTEUR.ID_AUTEUR%TYPE, VAL_NOM AUTEUR.NOM%TYPE, VAL_PRENOM AUTEUR.PRENOM%TYPE) IS
    IS_EXISTING NUMBER;
BEGIN
    SELECT COUNT(*) INTO IS_EXISTING FROM AUTEUR WHERE NOM = VAL_NOM AND PRENOM = VAL_PRENOM AND ID_AUTEUR != VAL_ID_AUTEUR;
    IF IS_EXISTING = 0 THEN
        UPDATE AUTEUR SET NOM = VAL_NOM, PRENOM = VAL_PRENOM WHERE ID_AUTEUR = VAL_ID_AUTEUR;
        COMMIT;
    ELSE
        RAISE_APPLICATION_ERROR(-20002, 'L''auteur existe déjà.');
    END IF;
END;
