CREATE SEQUENCE GENRE_SEQ INCREMENT BY 1 START WITH 12;

CREATE OR REPLACE FUNCTION CREER_GENRE(VAL_NOM GENRE.NOM%TYPE) RETURN NUMBER IS
    VAL_NEW_ID GENRE.ID_GENRE%TYPE;
    IS_EXISTING NUMBER;
BEGIN
    SELECT COUNT(*) INTO IS_EXISTING FROM GENRE WHERE NOM = VAL_NOM;
    IF IS_EXISTING > 0 THEN
        RAISE_APPLICATION_ERROR(-20001, 'Le genre existe déjà.');
        RETURN 0;
    END IF;

    SELECT GENRE_SEQ.NEXTVAL INTO VAL_NEW_ID FROM DUAL;
    INSERT INTO GENRE (ID_GENRE, NOM) VALUES (VAL_NEW_ID, VAL_NOM);
    COMMIT;

    RETURN VAL_NEW_ID;
END;


CREATE OR REPLACE PROCEDURE SUPPRIMER_GENRE(VAL_ID_GENRE GENRE.ID_GENRE%TYPE) IS
    IS_EXISTING NUMBER;
BEGIN
    SELECT COUNT(*) INTO IS_EXISTING FROM GENRE WHERE ID_GENRE = VAL_ID_GENRE;
    IF IS_EXISTING > 0 THEN
        DELETE FROM LIVRE WHERE GENRE = VAL_ID_GENRE;
        DELETE FROM GENRE WHERE ID_GENRE = VAL_ID_GENRE;
        COMMIT;
    ELSE
        RAISE_APPLICATION_ERROR(-20002, 'Le genre n''existe pas.');
    END IF;
END;

CREATE OR REPLACE PROCEDURE MODIFIER_GENRE(VAL_ID_GENRE GENRE.ID_GENRE%TYPE, VAL_NOM GENRE.NOM%TYPE) IS
    IS_EXISTING NUMBER;
BEGIN
    SELECT COUNT(*) INTO IS_EXISTING FROM GENRE WHERE NOM = VAL_NOM;
    IF IS_EXISTING = 0 THEN
        UPDATE GENRE SET NOM = VAL_NOM WHERE ID_GENRE = VAL_ID_GENRE;
        COMMIT;
    ELSE
        RAISE_APPLICATION_ERROR(-20002, 'Le genre existe déjà.');
    END IF;
END;