CREATE OR REPLACE PROCEDURE CREER_LIVRE(
    VAL_ISBN LIVRE.ISBN%TYPE,
    VAL_TITRE LIVRE.TITRE%TYPE,
    VAL_GENRE LIVRE.GENRE%TYPE,
    VAL_NB_PAGES LIVRE.NB_PAGES%TYPE,
    VAL_NB_EXEMPLAIRES LIVRE.NB_EXEMPLAIRES%TYPE,
    VAL_ID_AUTEUR LIVRE.ID_AUTEUR%TYPE) IS
    IS_EXISTING NUMBER;
BEGIN
    SELECT COUNT(*) INTO IS_EXISTING FROM LIVRE WHERE ISBN = VAL_ISBN;
    IF IS_EXISTING = 0 THEN
        INSERT INTO LIVRE (ISBN, TITRE, GENRE, NB_PAGES, NB_EXEMPLAIRES, ID_AUTEUR)
        VALUES (VAL_ISBN, VAL_TITRE, VAL_GENRE, VAL_NB_PAGES, VAL_NB_EXEMPLAIRES, VAL_ID_AUTEUR);
        COMMIT;
    ELSE
        RAISE_APPLICATION_ERROR(-20001, 'Le livre existe déjà.');
    END IF;
END;


CREATE OR REPLACE PROCEDURE SUPPRIMER_LIVRE(VAL_ISBN LIVRE.ISBN%TYPE) IS
    IS_EXISTING NUMBER;
BEGIN
    SELECT COUNT(*) INTO IS_EXISTING FROM LIVRE WHERE ISBN = VAL_ISBN;
    IF IS_EXISTING > 0 THEN
        DELETE FROM LIVRE WHERE ISBN = VAL_ISBN;
        COMMIT;
    ELSE
        RAISE_APPLICATION_ERROR(-20002, 'Le livre n''existe pas.');
    END IF;
END;


CREATE OR REPLACE PROCEDURE MODIFIER_LIVRE(
    VAL_ISBN LIVRE.ISBN%TYPE,
    VAL_TITRE LIVRE.TITRE%TYPE,
    VAL_GENRE LIVRE.GENRE%TYPE,
    VAL_NB_PAGES LIVRE.NB_PAGES%TYPE,
    VAL_NB_EXEMPLAIRES LIVRE.NB_EXEMPLAIRES%TYPE,
    VAL_ID_AUTEUR LIVRE.ID_AUTEUR%TYPE) IS
    IS_EXISTING NUMBER;
BEGIN
    SELECT COUNT(*) INTO IS_EXISTING FROM LIVRE WHERE TITRE = VAL_TITRE AND GENRE = VAL_GENRE AND NB_PAGES = VAL_NB_PAGES AND NB_EXEMPLAIRES = VAL_NB_EXEMPLAIRES AND ID_AUTEUR = VAL_ID_AUTEUR AND ISBN != VAL_ISBN;
    IF IS_EXISTING = 0 THEN
        UPDATE LIVRE SET TITRE = VAL_TITRE, GENRE = VAL_GENRE, NB_PAGES = VAL_NB_PAGES, NB_EXEMPLAIRES = VAL_NB_EXEMPLAIRES, ID_AUTEUR = VAL_ID_AUTEUR WHERE ISBN = VAL_ISBN;
        COMMIT;
    ELSE
        RAISE_APPLICATION_ERROR(-20002, 'Le livre existe déjà.');
    END IF;
END;
