CREATE SEQUENCE PRET_SEQ INCREMENT BY 1 START WITH 41;

CREATE OR REPLACE FUNCTION CREER_PRET (
    VAL_DATE_EMPRUNT IN PRET.DATE_EMPRUNT%TYPE,
    VAL_DUREE IN PRET.DUREE%TYPE,
    VAL_DATE_RETOUR_EFFECTIVE IN PRET.DATE_RETOUR_EFFECTIVE%TYPE,
    VAL_ISBN IN PRET.ISBN%TYPE,
    VAL_ID_USAGER IN PRET.ID_USAGER%TYPE
) RETURN PRET.ID_PRET%TYPE IS
    VAL_NEW_ID PRET.ID_PRET%TYPE;
    IS_EXISTING NUMBER;
BEGIN
    SELECT COUNT(*) INTO IS_EXISTING FROM PRET WHERE DATE_EMPRUNT = VAL_DATE_EMPRUNT AND DUREE = VAL_DUREE AND DATE_RETOUR_EFFECTIVE = VAL_DATE_RETOUR_EFFECTIVE AND ISBN = VAL_ISBN AND ID_USAGER = VAL_ID_USAGER;

    IF IS_EXISTING > 0 THEN
        RAISE_APPLICATION_ERROR(-20001, 'Le prêt existe déjà.');
        RETURN 0;
    END IF;

    SELECT PRET_SEQ.NEXTVAL INTO VAL_NEW_ID FROM DUAL;
    INSERT INTO PRET (ID_PRET, DATE_EMPRUNT, DUREE, DATE_RETOUR_EFFECTIVE, ISBN, ID_USAGER)
    VALUES (VAL_NEW_ID, VAL_DATE_EMPRUNT, VAL_DUREE, VAL_DATE_RETOUR_EFFECTIVE, VAL_ISBN, VAL_ID_USAGER);
    COMMIT;

    RETURN VAL_NEW_ID;
END;


CREATE OR REPLACE PROCEDURE SUPPRIMER_PRET(VAL_ID_PRET PRET.ID_PRET%TYPE) IS
    IS_EXISTING NUMBER;
BEGIN
    SELECT COUNT(*) INTO IS_EXISTING FROM PRET WHERE ID_PRET = VAL_ID_PRET;
    IF IS_EXISTING > 0 THEN
        DELETE FROM PRET WHERE ID_PRET = VAL_ID_PRET;
        COMMIT;
    ELSE
        RAISE_APPLICATION_ERROR(-20002, 'Le prêt n''existe pas.');
    END IF;
END;


CREATE OR REPLACE PROCEDURE MODIFIER_PRET(VAL_ID_PRET PRET.ID_PRET%TYPE, VAL_DATE_EMPRUNT PRET.DATE_EMPRUNT%TYPE, VAL_DUREE PRET.DUREE%TYPE, VAL_DATE_RETOUR_EFFECTIVE PRET.DATE_RETOUR_EFFECTIVE%TYPE, VAL_ISBN PRET.ISBN%TYPE, VAL_ID_USAGER PRET.ID_USAGER%TYPE) IS
    IS_EXISTING NUMBER;
BEGIN
    SELECT COUNT(*) INTO IS_EXISTING FROM PRET WHERE DATE_EMPRUNT = VAL_DATE_EMPRUNT AND DUREE = VAL_DUREE AND DATE_RETOUR_EFFECTIVE = VAL_DATE_RETOUR_EFFECTIVE AND ISBN = VAL_ISBN AND ID_USAGER = VAL_ID_USAGER AND ID_PRET != VAL_ID_PRET;
    IF IS_EXISTING = 0 THEN
        UPDATE PRET SET DATE_EMPRUNT = VAL_DATE_EMPRUNT, DUREE = VAL_DUREE, DATE_RETOUR_EFFECTIVE = VAL_DATE_RETOUR_EFFECTIVE, ISBN = VAL_ISBN, ID_USAGER = VAL_ID_USAGER WHERE ID_PRET = VAL_ID_PRET;
        COMMIT;
    ELSE
        RAISE_APPLICATION_ERROR(-20002, 'Le prêt existe déjà.');
    END IF;
END;