CREATE SEQUENCE USAGER_SEQ INCREMENT BY 1 START WITH 11;

CREATE OR REPLACE FUNCTION CREER_USAGER (
    VAL_NOM IN USAGER.NOM%TYPE,
    VAL_PRENOM IN USAGER.PRENOM%TYPE,
    VAL_ANNEE_NAISSANCE IN USAGER.ANNEE_NAISSANCE%TYPE,
    VAL_TARIF_REDUIT IN USAGER.TARIF_REDUIT%TYPE
) RETURN USAGER.ID_USAGER%TYPE IS
    VAL_NEW_ID USAGER.ID_USAGER%TYPE;
    IS_EXISTING NUMBER;

BEGIN
    SELECT COUNT(*) INTO IS_EXISTING FROM USAGER WHERE NOM = VAL_NOM AND PRENOM = VAL_PRENOM;

    IF IS_EXISTING > 0 THEN
        RAISE_APPLICATION_ERROR(-20001, 'L''usager existe déjà.');
        RETURN 0;
    END IF;

    SELECT USAGER_SEQ.NEXTVAL INTO VAL_NEW_ID FROM DUAL;
    INSERT INTO USAGER (ID_USAGER, NOM, PRENOM, ANNEE_NAISSANCE, TARIF_REDUIT)
    VALUES (VAL_NEW_ID, VAL_NOM, VAL_PRENOM, VAL_ANNEE_NAISSANCE, VAL_TARIF_REDUIT);
    COMMIT;

    RETURN VAL_NEW_ID;
END;


CREATE OR REPLACE PROCEDURE SUPPRIMER_USAGER(VAL_ID_USAGER USAGER.ID_USAGER%TYPE) IS
    IS_EXISTING NUMBER;
BEGIN
    SELECT COUNT(*) INTO IS_EXISTING FROM USAGER WHERE ID_USAGER = VAL_ID_USAGER;
    IF IS_EXISTING > 0 THEN
        DELETE FROM USAGER WHERE ID_USAGER = VAL_ID_USAGER;
        COMMIT;
    ELSE
        RAISE_APPLICATION_ERROR(-20002, 'L''usager n''existe pas.');
    END IF;
END;


CREATE OR REPLACE PROCEDURE MODIFIER_USAGER(VAL_ID_USAGER USAGER.ID_USAGER%TYPE, VAL_NOM USAGER.NOM%TYPE, VAL_PRENOM USAGER.PRENOM%TYPE, VAL_ANNEE_NAISSANCE USAGER.ANNEE_NAISSANCE%TYPE, VAL_TARIF_REDUIT USAGER.TARIF_REDUIT%TYPE) IS
    IS_EXISTING NUMBER;
BEGIN
    SELECT COUNT(*) INTO IS_EXISTING FROM USAGER WHERE NOM = VAL_NOM AND PRENOM = VAL_PRENOM AND ANNEE_NAISSANCE = VAL_ANNEE_NAISSANCE;
    IF IS_EXISTING = 0 THEN
        UPDATE USAGER SET NOM = VAL_NOM, PRENOM = VAL_PRENOM, ANNEE_NAISSANCE = VAL_ANNEE_NAISSANCE, TARIF_REDUIT = VAL_TARIF_REDUIT WHERE ID_USAGER = VAL_ID_USAGER;
        COMMIT;
    ELSE
        RAISE_APPLICATION_ERROR(-20002, 'L''usager existe déjà.');
    END IF;
END;
